version: "3.9"
services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build: .
    command: uvicorn api.app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file: .env
    volumes:
      - ./:/app
    depends_on:
      - mongo
    ports:
      - "8000:8000"

  bot:
    build: .
    command: python -m bot.app.main
    env_file: .env
    volumes:
      - ./:/app
    depends_on:
      - api

volumes:
  mongo_data:
